<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageId>TICinema.Contracts</PackageId>
		<Version>1.0.31</Version>
		<Authors>TICinema</Authors>
		<Company>TICinema</Company>
		<Description>gRPC contracts for TCinema microservices.</Description>

		<ContentTargetFolders>content</ContentTargetFolders>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
		<PackageReference Include="Grpc.Tools" Version="2.76.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\Identity\auth.proto" Pack="true" GrpcServices="Both" />
		<Protobuf Include="Protos\Identity\account.proto" Pack="true" GrpcServices="Both" />
		<Protobuf Include="Protos\users.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\media.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\category.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\movie.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\theater.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\hall.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\seat.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\screening.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\payment.proto" GrpcServices="Both" />
	</ItemGroup>

</Project>